// Code generated by MockGen. DO NOT EDIT.
// Source: domain/driver/service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	request "bit-driver-location-service/request"
	response "bit-driver-location-service/response"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryImplementation is a mock of RepositoryImplementation interface.
type MockRepositoryImplementation struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryImplementationMockRecorder
}

// MockRepositoryImplementationMockRecorder is the mock recorder for MockRepositoryImplementation.
type MockRepositoryImplementationMockRecorder struct {
	mock *MockRepositoryImplementation
}

// NewMockRepositoryImplementation creates a new mock instance.
func NewMockRepositoryImplementation(ctrl *gomock.Controller) *MockRepositoryImplementation {
	mock := &MockRepositoryImplementation{ctrl: ctrl}
	mock.recorder = &MockRepositoryImplementationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryImplementation) EXPECT() *MockRepositoryImplementationMockRecorder {
	return m.recorder
}

// FindNearestDriverByLocation mocks base method.
func (m *MockRepositoryImplementation) FindNearestDriverByLocation(loc request.CustomerLocation) ([]response.DriverLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNearestDriverByLocation", loc)
	ret0, _ := ret[0].([]response.DriverLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNearestDriverByLocation indicates an expected call of FindNearestDriverByLocation.
func (mr *MockRepositoryImplementationMockRecorder) FindNearestDriverByLocation(loc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNearestDriverByLocation", reflect.TypeOf((*MockRepositoryImplementation)(nil).FindNearestDriverByLocation), loc)
}
